name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PySide6

      - name: Build GUI executable
        run: |
          pyinstaller --onefile --windowed --name gpsd-timesync-gui \
            --hidden-import PySide6.QtCore \
            --hidden-import PySide6.QtWidgets \
            --hidden-import PySide6.QtGui \
            gpsd-timesync-gui.py

      - name: Build CLI executable
        run: pyinstaller --onefile --name gpsd-timesync-cli gpsd-timesync-cli.py

      - name: Archive build artifacts
        run: |
          mkdir -p ./artifacts
          mv dist/gpsd-timesync-gui ./artifacts/
          mv dist/gpsd-timesync-cli ./artifacts/

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
